services:
  db:
    ports:
      - "5432:5432"

  backend:
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      SYNC_DB: "false"
      # commenting out
      # JWT_SECRET: ${JWT_SECRET}
      # JWT_EXPIRE: ${JWT_EXPIRE:-7d}
    ports:
      - "8000:8000"

  frontend:
    environment:
      VITE_DOCKER: "true"
      CHOKIDAR_USEPOLLING: "true"
    build: ./frontend
    volumes:
      - ./frontend/website:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "5173:5173"

  worker:
    profiles: ["ml"]
