services:
  db:
    ports:
      - "5432:5432"

  backend:
    environment:
      NODE_ENV: development
      SYNC_DB: "false"
    ports:
      - "8000:8000"

  frontend:
    environment:
      VITE_DOCKER: true
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

  worker:
    profiles: ["ml"]