FROM node:20-alpine AS frontend-build

WORKDIR /frontend

COPY frontend/website/package*.json ./
RUN npm ci --omit=dev

COPY frontend/website/ ./
RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm ci --omit=dev

COPY backend/ ./

COPY --from=frontend-build /frontend/dist ./static

EXPOSE 8000

CMD ["node", "index.js"]